openapi: 3.0.0
info:
  title: School Management System API
  version: 1.0.0
  description: API pour la gestion scolaire
  contact:
    name: Support
    email: support@schoolmanagement.com

servers:
  - url: http://localhost:5000/api
    description: Serveur de développement

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        status:
          type: string
        message:
          type: string

paths:
  /health:
    get:
      tags:
        - System
      summary: Vérifie le statut de l'API
      responses:
        '200':
          description: API opérationnelle
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                  timestamp:
                    type: string
                    format: date-time
                  environment:
                    type: string
                  uptime:
                    type: number

  /auth/login:
    post:
      tags:
        - Authentication
      summary: Connexion utilisateur
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Connexion réussie